[package]
name = "rustari2600"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
clap = "3.0.0-rc.4"
minifb = "0.20"